#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  4 15:55:08 2019

@author: coreyshono
"""

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns; sns.set()

file_in = "../results-pickles/residuals_wNoise.P" 

df = pd.read_pickle(file_in) 

def distplot_fig(data, x, hue=None, row=None, col=None, legend=True, hist=False, **kwargs):
    """A figure-level distribution plot with support for hue, col, row arguments."""
    bins = kwargs.pop('bins', None)
    if (bins is None) and hist: 
        # Make sure that the groups have equal-sized bins
        bins = np.histogram_bin_edges(data[x].dropna())
    g = sns.FacetGrid(data, hue=hue, row=row, col=col)
    g.map(sns.distplot, x, bins=bins, hist=hist, **kwargs)
    if legend and (hue is not None) and (hue not in [x, row, col]):
        g.add_legend(title=hue) 
    return g   


# Plot avgs 
#print([c for c in df if "avg" in c])

avg_cols = [c for c in df if "avg" in c] 
var_cols = [c for c in df if "var" in c] 

df_avg = df[avg_cols] 
df_var = df[var_cols] 

df_avg = df_avg.stack().reset_index()
df_avg["Efficiency"] = "fixed"
df_var = df_var.stack().reset_index() 
df_var["Efficiency"] = "var" 

df_all = pd.concat([df_avg, df_var], axis=0) 
df_all = df_all.rename(columns={0: "SOC Residual (%)"}) 

plt.figure(dpi=200) 
sns.lineplot(x="Test(min)", y="SOC Residual (%)", hue="Efficiency", data=df_all) 
#sns.lineplot(x="Test(min)", y=0, data=df_var) 
plt.legend(loc='lower left')

distplot_fig(df_all, x="SOC Residual (%)", hue="Efficiency", hist=True, bins=np.arange(-0.2,0.2,0.02))
plt.savefig("./test.png", dpi=400)
