#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  4 15:55:08 2019

@author: coreyshono
"""

import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns; sns.set()

file_in = "../results-pickles/residuals.P" 

df = pd.read_pickle(file_in) 


# Plot avgs 
#print([c for c in df if "avg" in c])

avg_cols = [c for c in df if "avg" in c] 
var_cols = [c for c in df if "var" in c] 

df_avg = df[avg_cols] 
df_var = df[var_cols] 

df_avg = df_avg.stack().reset_index()
df_avg["Efficiency"] = "avg"
df_var = df_var.stack().reset_index() 
df_var["Efficiency"] = "var" 

df_all = pd.concat([df_avg, df_var], axis=0) 
df_all = df_all.rename(columns={0: "SOC Residual (%)"}) 

plt.figure(dpi=200) 
sns.lineplot(x="Test(min)", y="SOC Residual (%)", hue="Efficiency", data=df_all) 
#sns.lineplot(x="Test(min)", y=0, data=df_var) 
'''
plt.figure() 

for avg_col in avg_cols: 
    plt.plot(df[avg_col], color="tab:blue", alpha=0.2) 

for var_col in var_cols: 
    plt.plot(df[var_col], color="tab:orange", alpha=0.2) import seaborn as sns; sns.set()


"tab:blue"
"tab:orange" 
'''


